services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "5173"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - type: volume
        source: node_modules_cache
        target: /app/node_modules
    depends_on:
      - auth-service
      - profile-service
      - tuition-service
      - payment-service
      - email-service
    networks:
      - client-net

  auth-service:
    container_name: auth_service
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    expose:
      - "8001"
    volumes:
      - type: bind
        source: ./backend/auth-service
        target: /app
    depends_on:
      - mongodb
      - redis
    networks:
      - api-net

  profile-service:
    container_name: profile_service
    build:
      context: ./backend/profile-service
      dockerfile: Dockerfile
    expose:
      - "8002"
    volumes:
      - type: bind
        source: ./backend/profile-service
        target: /app
    depends_on:
      - mongodb
    networks:
      - api-net

  tuition-service:
    container_name: tuition_service
    build:
      context: ./backend/tuition-service
      dockerfile: Dockerfile
    expose:
      - "8003"
    volumes:
      - type: bind
        source: ./backend/tuition-service
        target: /app
    depends_on:
      - mongodb
    networks:
      - api-net

  payment-service:
    container_name: payment_service
    build:
      context: ./backend/payment-service
      dockerfile: Dockerfile
    expose:
      - "8004"
    volumes:
      - type: bind
        source: ./backend/payment-service
        target: /app
    depends_on:
      - mongodb
    networks:
      - api-net

  email-service:
    container_name: email_service
    build:
      context: ./backend/email-service
      dockerfile: Dockerfile
    expose:
      - "8005"
    volumes:
      - type: bind
        source: ./backend/email-service
        target: /app
    networks:
      - api-net

  otp-service:
    container_name: otp_service
    build:
      context: ./backend/otp-service
      dockerfile: Dockerfile
    expose:
      - "8006"
    volumes:
      - type: bind
        source: ./backend/otp-service
        target: /app
    depends_on:
      - redis
    networks:
      - api-net

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - api-net

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    expose:
      - "6379"
    networks:
      - api-net

  api-gateway:
    image: nginx:1.25-alpine
    container_name: api_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - auth-service
      - profile-service
      - tuition-service
      - payment-service
      - email-service
    networks:
      - api-net
      - client-net

networks:
  api-net:
  client-net:

volumes:
  mongodb_data:
  node_modules_cache:
